name: CI

on:
  push:
    branches: [develop]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        run: echo "hello"

  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        run: echo "hello"

  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        run: echo "hello"
